print("Welcome to the Band Name Generator")
city = input("whats the name of the city you grew up in? ")
print(city)
pet = input("whats the name of your pet? ")
print("Your band name could be " + city + " " + pet)
